/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.jupiter.api.Assertions.*;
import org.junit.api.Test;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
